CREATE TABLE IF NOT EXISTS activity_logs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  admin_id INT UNSIGNED NULL,
  admin_name VARCHAR(180) NULL,
  admin_email VARCHAR(180) NULL,
  role_name VARCHAR(80) NULL,
  action VARCHAR(120) NOT NULL,
  module VARCHAR(120) NOT NULL,
  entity_type VARCHAR(120) NULL,
  entity_id VARCHAR(120) NULL,
  entity_name VARCHAR(255) NULL,
  old_values JSON NULL,
  new_values JSON NULL,
  changes JSON NULL,
  description TEXT NULL,
  ip_address VARCHAR(80) NULL,
  user_agent TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_activity_logs_admin_id (admin_id),
  INDEX idx_activity_logs_action (action),
  INDEX idx_activity_logs_module (module),
  INDEX idx_activity_logs_entity_type (entity_type),
  INDEX idx_activity_logs_entity_id (entity_id),
  INDEX idx_activity_logs_created_at (created_at)
);
